-- Change the id column of active_semester so we can insert/upsert explicit values
ALTER TABLE public.active_semester ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.active_semester ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
